
- name: Check for Operating and packages
  become: true
  become_user: root
  yum:
     name: docker
     state: latest
- debug:
     msg: 'We are installing Docker as docker is not install on remote machine'  
  when: ansible_facts['distribution'] == 'CentOS'
